# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

guzzle:
    clients:
        api_payment:
            base_url: "http://tivat.sistem48.me"

            # custom headers
            headers:
                Accept: "application/json"

            # guzzle client options (full description here: http://guzzle.readthedocs.org/en/latest/request-options.html)
            # NOTE: "headers" option is not accepted here as it is provided as described above.
            options:
                auth:
                    - acme     # login
                    - pa55w0rd # password
                timeout: 30

            # plugin settings
            plugin:
                wsse:
                    username: acme
                    password: pa55w0rd

        api_crm:
            base_url: "http://api.crm.tld"
            headers:
                Accept: "application/json"